
ktor {
  deployment { port = 8080 }
  application { modules = [ org.messanger.project.ApplicationKt.module ]}
}
jwt {
  secret = ${?JWT_SECRET}
  issuer = "messanger-server"
  audience = "messanger-client"
  realm = "messanger-app"
}

database {
url = ${?DB_URL}
user = ${?DB_USER}
password = ${?DB_PASSWORD}
}